### ISSUE TITLE
Congratulation message

### ISSUE THREAD

**Issue by theonlyNischal** [MegaMind98/My-SGPA#1]
Congratulation text should appear **after we add all the subjects**.
We can't be selected in Dean list **until we pass** in all the subject.

**Comment by MegaMind98** [comment]
We do not ask for the total number of subjects beforehand (who would like to make extra click, that might be confusing), so it is impossible to predict user's mind with 100% accuracy. I cannot think of any solution right now, if you have any please let me know. 

And, as of now, I've disabled that section until we hear from you. Watch this: https://github.com/MegaMind98/My-SGPA/commit/b236a53fa3cc5516f70bea0ce3a56bdaf659e95c
