### ISSUE TITLE
Congratulations! You've made to the Dean's List. Error

### ISSUE THREAD

**Issue by InfoDevkota** [MegaMind98/My-SGPA#3]
When we select Grade before selecting the Credit Hour, this shows That Congratulations message. Which i think is a error.
![screenshot from 2018-10-03 22-24-54](https://user-images.githubusercontent.com/15100881/46425448-72656880-c75b-11e8-91d4-902548c4cae9.png)

**Comment by MegaMind98** [comment]
Thank you @InfoDevkota for pointing out the issue.

PS This repository hasn't been synced with the live version of the website.
